config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :posts do
    resources :comments
  end
  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  validates :image, presence: true
  validates :user_id, presence: true
  validates :caption, length: {minimum: 3, maximum: 300}
  has_attached_file :image, styles: { :medium => "640x" }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :user_name, presence: true, length: { minimum: 4, maximum: 16 }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_post

  def create
    @comment = @post.comments.build(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    else
      flash[:alert] = "There was something wrong with adding your comment."
      render root_path
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])

    if @comment.user_id == current_user.id
      @comment.delete
      respond_to do |format|
        format.html { redirect_to root_path }
        format.js
      end
    end
  end

  end

  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def set_post
      @post = Post.find(params[:post_id])
    end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :owned_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  # Controller to manage edit view
  def edit
  end

  # Controller that handle updating logic
  def update
    if @post.update(post_params)
      flash[:success] = "Post updated successfully!"
      redirect_to(post_path(@post))
    else
      flash[:alert] = "You post couldn't be updated! Check the form and try again!"
      redirect_to :edit
    end
  end

  # Deletes post
  def destroy
    @post.destroy
    redirect_to posts_path
  end

  # Using the data in out form for submission
  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:success] = "You post has been created successfully."
      redirect_to posts_path
    else
      flash[:alert] = "Your new post couldn't be created. Check the form and try again."
      render :new
    end
  end

  # Show a single post
  def show
  end

  private

    # Here we define the exact data we want to accpet as the parameters.
    def post_params
      params.require(:post).permit(:image, :caption)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def owned_post
      unless current_user = @post.user
        flash[:alert] = "That post doesn't belong to you!"
        redirect_to root_path
      end
    end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def alert_for(flash_type)
  {
    success: 'alert-success text-center',
    error: 'alert-danger text-center',
    alert: 'alert-warning text-center',
    notice: 'alert-info text-center'
  }[flash_type.to_sym] || flash_type.to_s
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.haml
#comment
  .user-name
    = comment.user.user_name
  .comment-content
    = comment.content
  - if comment.user == current_user
    = link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do
      %span(class="glyphicon glyphicon-remove delete-comment")

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%= j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')

app/views/comments/destroy.js.erb
$('#comments_<%= @post.id %>').html("<%= j render @post.comments, post: @post, comment: @comment %>");

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Photolol
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

%body
  = render 'partials/navbar'
  -flash.each do |name, msg|
    .container
    = content_tag :div, msg, class: [:alert, alert_for(name)]
  = yield

app/views/partials/_form.html.haml
.form-wrapper
  = simple_form_for @post, html: { class: 'form-horizontal', multipart: true } do |f|
    .form-group
      = f.input :image
    .form-group.text-center
      = f.input :caption
    .form-group.text-center
      = f.button :submit, class: 'btn-success'

app/views/partials/_navbar.html.haml
%nav.navbar.navbar-default
  .navbar-container
    .navbar-header
      %button.navbar-toggle.collapsed{"data-target" => "#bs-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
        %span.sr-only Toggle Navigation
        %span.icon-bar
        %span.icon-bar
      .navbar-brand= link_to "Photolol", root_path
    .collapse.navbar-collapse#bs-navbar-collapse-1
      %ul.nav.navbar-nav.navbar-right
        - if user_signed_in?
          %li
            = link_to "New Post", new_post_path
          %li
            = link_to "Logout", destroy_user_session_path, method: :delete
        - else
          %li
            = link_to "Login", new_user_session_path
          %li
            = link_to "Register", new_user_registration_path

app/views/partials/_post.html.haml
.posts-wrapper
  .post
    .post-head
      .thumb-img
      .user-name
        = post.user.user_name
      .time-ago
        = time_ago_in_words post.created_at
    .image.center-block
      = link_to (image_tag post.image.url(:medium), class:'img-responsive'), post_path(post)
    .post-bottom
      .caption
        .user-name
          = post.user.user_name
        = post.caption
      .comments{id: "comments_#{post.id}"}
        - if post.comments
          = render post.comments, post: post
    .comment-like-form.row
      .like-button.col-sm-1
        %span(class="glyphicon glyphicon-heart-empty")
      .comment-form.col-sm-11
        = form_for([post, post.comments.new], remote: true) do |f|
          = f.text_field :content, placeholder: 'Add a comment...', class: "comment_content", id: "comment_content_#{post.id}"

app/views/posts/edit.html.haml
.text-center
  = image_tag @post.image.url(:medium)

= render 'partials/form'

.text-center.edit-links
  = link_to "Delete Post", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }
  |
  = link_to "cancel", posts_path

app/views/posts/index.html.haml
.posts-wrapper.row
  -@posts.each do |post|
    = render 'partials/post', post: post

app/views/posts/new.html.haml
= render 'partials/form'

app/views/posts/show.html.haml
= render 'partials/post', post: @post
- if @post.user.id == current_user.id
  .text-center.edit-links
    = link_to "Cancel", posts_path
    |
    = link_to "Edit Post", edit_post_path(@post)
- else
  .text-center.edit-links
    =link_to "Cancel", posts_path